version: '3.9'

services:

  backend:
    image: mycreativeapps/myspiritualassistant:1.0.18
    container_name: myspiritualassistant-backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env

  # redis-cache:
  #   image: redis:alpine
  #   container_name: redis-cache
  #   restart: always
  #   ports:
  #     - "6379:6379"
  #   command: redis-server --appendonly yes
  #   volumes:
  #     - redis_data:/data

  postgres-dev:
    image: postgres:16
    container_name: postgres-dev
    restart: always
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: VH4vaDax7QqfKvOtXJNs3SDor
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data

  postgres-prod:
    image: postgres:16
    container_name: postgres-prod
    restart: always
    environment:
      POSTGRES_DB: prod
      POSTGRES_USER: prod_user
      POSTGRES_PASSWORD: BWik9iVpwG2K26djMHMcOk3Xq
    ports:
      - "5433:5432"
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data


volumes:
  postgres_dev_data:
  postgres_prod_data:
