import { StyleSheet } from 'react-native';
import { ThemeColors } from '../../config/styles';

const createStyles = (colors: ThemeColors) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    header: {
      paddingVertical: 24,
      alignItems: 'center',
      backgroundColor: colors.primary,
      borderBottomLeftRadius: 30,
      borderBottomRightRadius: 30,
      elevation: 4,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 4,
    },
    avatar: {
      backgroundColor: colors.surface,
      elevation: 8,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 6,
    },
    avatarContainer: {
      position: 'relative',
    },
    editButton: {
      position: 'absolute',
      bottom: 0,
      left: 0,
      backgroundColor: colors.surface,
      borderRadius: 20,
      width: 36,
      height: 36,
      justifyContent: 'center',
      alignItems: 'center',
      elevation: 10,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
      borderWidth: 2,
      borderColor: colors.primary,
    },
    qrButton: {
      position: 'absolute',
      bottom: 0,
      right: 0,
      backgroundColor: colors.surface,
      borderRadius: 20,
      width: 36,
      height: 36,
      justifyContent: 'center',
      alignItems: 'center',
      elevation: 10,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
      borderWidth: 2,
      borderColor: colors.primary,
    },
    modalContainer: {
      backgroundColor: 'rgba(0,0,0,0.5)',
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
    },
    modalContent: {
      backgroundColor: colors.surface,
      padding: 24,
      borderRadius: 24,
      alignItems: 'center',
      width: '80%',
      elevation: 20,
    },
    qrTitle: {
      fontSize: 20,
      fontWeight: 'bold',
      marginBottom: 8,
      color: colors.primary,
    },
    qrSubtitle: {
      fontSize: 14,
      color: colors.subtext,
      marginBottom: 20,
      textAlign: 'center',
    },
    userName: {
      marginTop: 16,
      fontSize: 24,
      fontWeight: 'bold',
      color: colors.white,
    },
    userEmail: {
      fontSize: 16,
      color: colors.white,
    },
    content: {
      padding: 16,
    },
    section: {
      marginBottom: 24,
    },
    sectionTitle: {
      fontSize: 18,
      fontWeight: 'bold',
      marginBottom: 12,
      color: colors.primary,
      marginLeft: 4,
    },
    infoCard: {
      backgroundColor: colors.surface,
      borderRadius: 16,
      padding: 16,
      elevation: 2,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.1,
      shadowRadius: 2,
    },
    infoRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 12,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    infoLabel: {
      fontSize: 12,
      color: colors.primary,
      fontWeight: 'bold',
      textTransform: 'uppercase',
      letterSpacing: 1,
      marginBottom: 2,
    },
    infoValue: {
      fontSize: 16,
      color: colors.text,
      fontWeight: 'bold',
    },
    iconWrapper: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: colors.primary + '10', // 10% opacity
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 12,
    },
    logoutButton: {
      marginTop: 24,
      borderRadius: 12,
      paddingVertical: 8,
      borderColor: colors.error,
    },
    logoutLabel: {
      color: colors.error,
      fontWeight: 'bold',
    },
  });

export default createStyles;
